import AppKit

enum ShelfBatchTransfer {
    enum TransferError: LocalizedError {
        case emptySelection
        case unavailable(String)
        case mixedCopy

        var errorDescription: String? {
            switch self {
            case .emptySelection: return "Select at least one item first."
            case .unavailable(let title): return "“\(title)” is no longer available. Nothing was transferred."
            case .mixedCopy: return "Copy text and files separately, or drag the selection to an app that accepts those types."
            }
        }
    }

    struct Entry {
        let title: String
        let fileURL: URL?
        let text: String?
        let rtf: Data?

        func writer() -> NSPasteboardItem {
            let payload = NSPasteboardItem()
            if let fileURL {
                payload.setString(fileURL.absoluteString, forType: .fileURL)
            } else if let text {
                payload.setString(text, forType: .string)
                if let rtf { payload.setData(rtf, forType: .rtf) }
            }
            payload.setString("FlowShelf", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
            return payload
        }
    }

    static func prepare(_ items: [ShelfItem], imageURL: (ShelfItem) -> URL?) throws -> [Entry] {
        guard !items.isEmpty else { throw TransferError.emptySelection }
        return try items.map { item in
            switch item.kind {
            case .file, .image, .screenshot:
                var url: URL?
                if item.kind == .file {
                    if let bookmark = item.fileBookmark {
                        var stale = false
                        url = try? URL(resolvingBookmarkData: bookmark, options: [.withoutUI, .withoutMounting],
                                       relativeTo: nil, bookmarkDataIsStale: &stale)
                    }
                    if url == nil, let path = item.filePath { url = URL(fileURLWithPath: path) }
                } else {
                    url = imageURL(item)
                }
                guard let url, url.isFileURL, FileManager.default.isReadableFile(atPath: url.path) else {
                    throw TransferError.unavailable(item.title)
                }
                return Entry(title: item.title, fileURL: url, text: nil, rtf: nil)
            default:
                let text = item.text ?? item.preview
                guard !text.isEmpty else { throw TransferError.unavailable(item.title) }
                return Entry(title: item.title, fileURL: nil, text: text,
                             rtf: ClipboardPayload.boundedRTF(item.richTextRTF))
            }
        }
    }

    static func copyWriters(_ entries: [Entry]) throws -> [NSPasteboardItem] {
        guard !entries.isEmpty else { throw TransferError.emptySelection }
        if entries.allSatisfy({ $0.fileURL != nil }) {
            var seen = Set<URL>()
            return entries.filter { seen.insert($0.fileURL!.standardizedFileURL).inserted }.map { $0.writer() }
        }
        guard entries.allSatisfy({ $0.text != nil }) else { throw TransferError.mixedCopy }
        return [Entry(title: "Selected text", fileURL: nil,
                      text: entries.compactMap(\.text).joined(separator: "\n\n"), rtf: nil).writer()]
    }
}
