import AppKit

enum ClipboardPrivacyRules {
    static let maximumCustomRules = 128
    static let builtInTypes: [String] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type"
    ]

    static func normalized(_ input: String) -> String {
        input.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    static func validationMessage(for input: String, existing: [String]) -> String? {
        let value = normalized(input)
        guard !value.isEmpty else { return "Enter an exact clipboard type name." }
        guard value.utf8.count <= 255 else { return "Type names must be 255 bytes or shorter." }
        guard !value.unicodeScalars.contains(where: CharacterSet.controlCharacters.contains) else {
            return "Use one type name without tabs or line breaks."
        }
        guard !value.contains("*") else { return "Use an exact type name, not a wildcard." }
        guard !builtInTypes.contains(value) else { return "This type is already protected by a built-in rule." }
        guard !existing.contains(value) else { return "This type is already in your list." }
        guard existing.count < maximumCustomRules else { return "Remove a rule before adding another (128 maximum)." }
        return nil
    }

    static func sanitized(_ values: [String]) -> [String] {
        var result: [String] = []
        for value in values {
            if validationMessage(for: value, existing: result) == nil {
                result.append(normalized(value))
            }
        }
        return result
    }

    static func shouldIgnore(_ pasteboard: NSPasteboard, customTypes: [String]) -> Bool {
        var types = Set((pasteboard.types ?? []).map(\.rawValue))
        for item in pasteboard.pasteboardItems ?? [] {
            types.formUnion(item.types.map(\.rawValue))
        }
        return shouldIgnore(types: types, customTypes: customTypes)
    }

    static func shouldIgnore(types: Set<String>, customTypes: [String]) -> Bool {
        !types.isDisjoint(with: Set(builtInTypes).union(customTypes))
    }
}
