import AppKit
import UniformTypeIdentifiers

/// Watches `NSPasteboard.general` and turns each new copy into a Shelf item.
/// Lightweight: polls `changeCount` rather than hooking the pasteboard.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let store = ShelfStore.shared
    private let settings = AppSettings.shared

    // Pasteboard markers used by privacy-conscious apps (password managers, etc.).
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private init() {}

    func start() {
        guard timer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        guard settings.clipboardEnabled, !settings.privateMode else { return }

        if settings.ignoreNextCopy {
            settings.ignoreNextCopy = false
            return
        }

        // Honor privacy markers — never store concealed/transient clipboard data.
        let types = Set(pb.types ?? [])
        if types.contains(concealedType) || types.contains(transientType) || types.contains(autoGeneratedType) {
            return
        }

        let frontApp = NSWorkspace.shared.frontmostApplication
        if settings.isExcluded(bundleID: frontApp?.bundleIdentifier) { return }
        let appName = frontApp?.localizedName

        capture(from: pb, sourceApp: appName)
    }

    private func capture(from pb: NSPasteboard, sourceApp: String?) {
        // 1. File URLs (dragged/copied files) — store as references, don't duplicate.
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           let url = urls.first, url.isFileURL {
            addFile(url: url, sourceApp: sourceApp)
            return
        }

        // 2. Image data.
        if let img = NSImage(pasteboard: pb), pb.data(forType: .tiff) != nil || pb.data(forType: .png) != nil {
            if let (rel, thumb) = store.storeImage(img, prefix: "clip") {
                store.add(ShelfItem(
                    kind: .image,
                    title: "Image",
                    preview: "Copied image",
                    sourceApp: sourceApp,
                    imageRelPath: rel,
                    thumbRelPath: thumb
                ))
            }
            return
        }

        // 3. Text / links.
        if let text = pb.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let isLink = text.looksLikeURL
            store.add(ShelfItem(
                kind: isLink ? .link : .text,
                title: isLink ? (URL(string: text)?.host ?? "Link") : text.firstLine(),
                preview: text.firstLine(max: 140),
                text: text,
                sourceApp: sourceApp
            ))
        }
    }

    private func addFile(url: URL, sourceApp: String?) {
        let bookmark = try? url.bookmarkData(options: .minimalBookmark)
        store.add(ShelfItem(
            kind: .file,
            title: url.lastPathComponent,
            preview: url.deletingLastPathComponent().path,
            sourceApp: sourceApp,
            fileBookmark: bookmark,
            filePath: url.path
        ))
    }
}
